create table usuarios
(
    id        integer generated by default as identity
        primary key,
    apellidos varchar(255),
    correo    varchar(255)
        unique,
    imagenurl varchar(255),
    nombre    varchar(255),
    password  varchar(255),
    telefono  varchar(255),
    tipo      varchar(255)
        constraint usuarios_tipo_check
            check ((tipo)::text = ANY ((ARRAY ['ADMIN'::character varying, 'USER'::character varying])::text[])),
    username  varchar(255)
        unique
);


INSERT INTO usuarios (id, apellidos, correo, imagenurl, nombre, password, telefono, tipo, username)
VALUES
-- Admin users
(1,'García Pérez', 'admin1@example.com', 'https://example.com/images/admin1.jpg', 'Carlos', 'admin123', '600123456', 'ADMIN', 'cgarcia'),
(2,'López Díaz', 'admin2@example.com', 'https://example.com/images/admin2.jpg', 'Lucía', 'admin456', '600654321', 'ADMIN', 'ldiaz'),

-- Regular users
(4,'Martínez Gómez', 'user1@example.com', 'https://example.com/images/user1.jpg', 'Elena', 'user123', '611111111', 'USER', 'emartinez'),
(5,'Sánchez Ruiz', 'user2@example.com', 'https://example.com/images/user2.jpg', 'Pablo', 'user456', '622222222', 'USER', 'psanchez'),
(6,'Fernández Torres', 'user3@example.com', 'https://example.com/images/user3.jpg', 'Laura', 'user789', '633333333', 'USER', 'lfernandez'),
(7,'Jiménez Romero', 'user4@example.com', 'https://example.com/images/user4.jpg', 'Jorge', 'user321', '644444444', 'USER', 'jjimenez'),
(8,'Navarro Morales', 'user5@example.com', 'https://example.com/images/user5.jpg', 'Ana', 'user654', '655555555', 'USER', 'anavarro');


create table hilos
(
    id_creador     integer
        constraint fkp8840cp8foho3btiqdd8p0uf1
            references usuarios,
    fecha_creacion timestamp(6),
    id             bigint generated by default as identity
        primary key,
    mensaje_count  bigint,
    visitas        bigint,
    votos          bigint,
    descripcion    varchar(255),
    titulo         varchar(255)
);

alter table hilos
    owner to localuser;



INSERT INTO public.hilos (id, titulo, descripcion, votos, mensaje_count, visitas, fecha_creacion, id_creador) VALUES
(1, '¿Cuál es tu framework favorito?', 'Comparte tus experiencias con Spring, Django, etc.', 5,2, 40, now(), 1),
(2, 'Problema con Thymeleaf', 'Me está dando un error de binding', 2, 5, 25, now(), 2),
(3, 'Recomendaciones de libros de Java', '¿Qué libros os ayudaron más?', 4,6, 15, now(), 4),
( 4,'¿Frontend o Backend?', 'Debate sano, por favor.', 6, 7, 50, now(), 5),
( 5,'Dudas con JPA', '¿Cómo hago joins en entidades?', 1, 42, 18, now(), 6),
(6, '¿Qué es un DTO?', 'No entiendo bien la diferencia con Entity', 3, 14, 22, now(), 7),
(7, 'Spring Security básico', '¿Cómo empiezo con roles?', 2, 12, 33, now(), 8);

create table mensajes
(
    id_escritor       integer
        constraint fkpnt5a5scw37aswlr8edhj3x0f
            references usuarios,
    fecha_publicacion timestamp(6),
    id                bigint generated by default as identity
        primary key,
    id_citado         bigint
        constraint fk3tdsmcgxvykxyekjd2aylh1b0
            references mensajes,
    id_hilo           bigint
        constraint fk3vdqpnq543faen0o71xj81ybn
            references hilos,
    votos             bigint,
    contenido         varchar(255)
);

alter table mensajes
    owner to localuser;



INSERT INTO public.mensajes (id, id_escritor, id_hilo, id_citado, contenido, fecha_publicacion, votos) VALUES
(1,2, 1, NULL, 'Primer mensaje del hilo ¿Cuál es tu framework favorito?', now() - interval '2 days', 6),
(2,4, 2, NULL, 'Inicio del hilo Problema con Thymeleaf.', now() - interval '1 day', 4);

INSERT INTO public.mensajes (id,id_escritor, id_hilo, id_citado, contenido, fecha_publicacion, votos) VALUES
(3,5, 1, 1, 'Totalmente de acuerdo, aunque también me gusta Django.', now() - interval '1 day 3 hours', 3),
(4,6, 2, 2, 'Yo también tuve ese problema, lo solucioné así...', now() - interval '12 hours', 5),
(5,7, 1, 1, 'Spring Boot es lo mejor para mí.', now() - interval '20 hours', 4);